### ISSUE TITLE
Error during installing dependencies

### ISSUE THREAD

**Issue by yuanze1024** [zzzyuqing/DreamMat#12]
# Env
I'm using a Nvidia official docker image as the base image on my 4090 Graphics card.
# Problems
## tiny-cuda-nn
During installing tiny-cuda-nn, an error occurred:
```log
...
[DreamMat/modules/tiny-cuda-nn/dependencies/fmt/src/format.cc](ninja: error: 'PATH/DreamMat/modules/tiny-cuda-nn/dependencies/fmt/src/format.cc', needed by 'PATH/DreamMat/modules/tiny-cuda-nn/bindings/torch/dependencies/fmt/src/format.o', missing and no known rule to make it)
...
```

Can be solved according to https://github.com/NVlabs/tiny-cuda-nn/issues/447.

## raytracing
And also, there got a `Eigen/Dense: No such file or directory` installing **raytracing**.
I checked that there is no such package in my env:
```shell
root@path# dpkg -s libeigen3-dev
dpkg-query: package 'libeigen3-dev' is not installed and no information is available
Use dpkg --info (= dpkg-deb --info) to examine archive files.
```
so I install it: 
```shell
apt update
apt install libeigen3-dev
```

**Comment by yuanze1024** [comment]
In case someone may meet the same problem.

**Comment by dongchen-yang** [comment]
My system has eigen installed by still have this problem. Fixed by adding a symbolic link `ln -s eigen3/Eigen Eigen`
