### ISSUE TITLE
Is there any way to make it work without using abandoned library: ashawkey/raytracing?

### ISSUE THREAD

**Issue by MrForExample** [zzzyuqing/DreamMat#3]
Hi, I really like the idea in this project, so I still want to make it work, but I just couldn't build [ashawkey/raytracing](https://github.com/ashawkey/raytracing), but I saw you have other renders implemented, so I wonder is there a way to use them instead?
I tried to change the settings in config files, e.g. `renderer_type: "nerf-volume-renderer"` `use_raytracing: false` `use_fix_views: false` but seems the code doesn't work with renderer type other than `raytracing-renderer`

**Comment by zzzyuqing** [comment]
The current implementation is based on this library. If you set use_raytracing to false and resort to split-sum approximation for rendering, it might not produce the results as shown in the paper. However, any other libraries or custom implementations that can assist in calculating ray intersections and bounces can serve as a substitute for this raytracing library. In addition, I plan to release a Docker image in the future, which might help resolve the issue with building the raytracing library.
