### ISSUE TITLE
No 'from_unet_inchannel' functions in ControlNetModel

### ISSUE THREAD

**Issue by CzzzzH** [zzzyuqing/DreamMat#4]
Hello, thanks for the great work!

The script of training controlnet uses ControlNetModel.from_unet_inchannel instead of ControlNetModel.from_unet, but it seems that there isn't such a function in my diffusers library. What is the version of diffusers you use? Or is it just the same as using ControlNetModel.from_unet?

**Comment by zzzyuqing** [comment]
Yes, in the newer versions of diffusers, you can directly use `ControlNetModel.from_unet`. Thanks for the reminder, I've updated the code.
