### ISSUE TITLE
Cannot build raytracing.

### ISSUE THREAD

**Issue by BlockyBard** [zzzyuqing/DreamMat#5]
What system is this tested on? I'm unable to get this https://github.com/ashawkey/raytracing built. Complains about eigen first and when I download and add Eigen to path still bunch of errors. An environment file or a container would be great.

**Comment by zzzyuqing** [comment]
This has been tested on Ubuntu 20.04 and CentOS 7. A Docker image will be available soon. In the meantime, I hope the following `environment.yml` file can help you.
[environment_yml.zip](https://github.com/user-attachments/files/15524906/environment_yml.zip)

**Comment by pramishp** [comment]
@zzzyuqing Thank you for open sourcing this great work ! I am facing the same issue while building raytracing. What's the update on this docker image ?

**Comment by zzzyuqing** [comment]
The Docker image has been released. Here is the link.
https://hub.docker.com/repository/docker/zzzyuqing/dreammat_image/general
