### ISSUE TITLE
Low VRAM

### ISSUE THREAD

**Issue by adksantosh** [zzzyuqing/DreamMat#6]
How do I run this on systems with low VRAM? I have a 16gb card but it runs out of memory.

**Comment by zzzyuqing** [comment]
Our method indeed requires a significant amount of VRAM, and we currently do not have a low VRAM usage implementation available. However, you can try to reduce the VRAM consumption through the following means, but be mindful that this might sacrifice the quality of the results:
- Render at 256\*256, then resize to 512\*512 to be used as the input for stable diffusion.
- Decrease the value of `system.geometry.shape_init_params`.
- Reduce the number of ray samples during rendering by adjusting `system.material.diffuse_sample_num` and `system.material.specular_sample_num`.
